export const GET_RECIPES = 'GET_RECIPES';
export const FETCH_RECIPE_FAILED = 'FETCH_RECIPE_FAILED';
export const FETCH_RECIPE_SUCCEDED = 'FETCH_RECIPE_SUCCEDED';
export const LIST_FOR_CALORIES = 'LIST_FOR_CALORIES';
export const SORT_CALORIES = 'SORT_CALORIES';
